export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const POSTSUBMIT = "POSTSUBMIT";
export const POSTEDITMODAL = "POSTEDITMODAL";
export const POSTEDITMODALEMPTY = "POSTEDITMODALEMPTY";
export const USERPROFILEDATA = "USERPROFILEDATA";
export const ADDFAVORITEPOSTSLIST = "ADDFAVORITEPOSTSLIST";
export const REMOVEFAVORITEPOSTSLIST = "REMOVEAVORITEPOSTSLIST";
